package tron

import (
	"io"
	"log/slog"
	"testing"

	bc "github.com/goexdev/goexchange/internal/blockchain"
)

// TestValidateAddress exercises the Base58Check parser on the
// kind of inputs the scanner and the REST handler need to filter on.
func TestValidateAddress(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		// Valid mainnet-format TRON address. The 21-byte payload is
		// {0x41, 0xab...} and the last 4 bytes of base58CheckEncode are
		// the double-sha256 checksum; flipping one byte breaks it.
		// This particular address is generated by base58_test.go so
		// we know its checksum is correct.
		{"TBdTs1DPTc8Qwy1764Lj94pKAuVg6JhXDA", true},
		// Wrong checksum: same payload with the last byte flipped.
		{"TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU8", false},
		// Empty string.
		{"", false},
		// EVM-style 0x... address (must reject - TRON is not EVM at
		// the address-encoding layer even though both use keccak256
		// internally).
		{"0x0000000000000000000000000000000000000000", false},
		// Bitcoin bech32: not Base58.
		{"bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4", false},
	}
	a := &Adapter{log: testLogger()}
	for _, tc := range cases {
		got := a.ValidateAddress(tc.in)
		if got != tc.want {
			t.Errorf("ValidateAddress(%q) = %v, want %v", tc.in, got, tc.want)
		}
	}
}

// TestParseTransferEventsContractFilter verifies that the contract
// address filter is applied correctly so the scanner only emits
// events for the token it cares about. The events are encoded in
// the same JSON shape the adapter writes into Transaction.Events.
func TestParseTransferEventsContractFilter(t *testing.T) {
	a := &Adapter{log: testLogger()}
	tx := bc.Transaction{
		Hash:   "abc",
		Status: bc.TxStatusSuccess,
		Events: []string{
			// USDT log (matching address, three topics).
			`{"address":"a614f803b6fd780986a42c79ec8394ade726993d","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000aabbccddeeff0011223344556677889900aabbcc","0x0000000000000000000000001122334455667788990aabbccddeeff001122334"],"data":"0x0000000000000000000000000000000000000000000000000000000005f5e100"}`,
			// Other token (no match).
			`{"address":"deadbeefdeadbeefdeadbeefdeadbeefdeadbeef","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x000000000000000000000000aabbccddeeff0011223344556677889900aabbcc","0x0000000000000000000000001122334455667788990aabbccddeeff001122334"],"data":"0x00"}`,
		},
	}
	events, err := a.ParseTransferEvents(tx, "41a614f803b6fd780986a42c79ec8394ade726993d")
	if err != nil {
		t.Fatalf("ParseTransferEvents: %v", err)
	}
	if len(events) != 1 {
		t.Fatalf("expected 1 event after contract filter, got %d", len(events))
	}
	if events[0].Amount.Int64() != 100_000_000 {
		t.Errorf("amount = %d, want 100000000", events[0].Amount.Int64())
	}
}

func testLogger() *slog.Logger {
	return slog.New(slog.NewTextHandler(io.Discard, nil))
}