services:
  postgres:
    image: postgres:16-alpine
    container_name: goexchange-postgres
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: exchange
    ports:
      - "5433:5432"
    volumes:
      - goexchange_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exchange"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: goexchange-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6388:6379"
    volumes:
      - goexchange_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  goexchange_pgdata:
  goexchange_redisdata:
