-- 0035 -- per-pair market-making bot (V1 MVP, BNB_USDT first)
--
-- One row per bot instance. Bot_id is the primary key and uses
-- the convention "<BASE>_<QUOTE>_mm_<n>" where <n> increments per
-- pair (so admins can stop and re-start the same pair without
-- colliding with prior runs).
--
-- Per-pair uniqueness: only one bot per pair may be in a
-- "live" status at any time. We enforce this with a partial
-- unique index on pair where status IN (SEEDING, READY, RUNNING,
-- STOPPING). A previous STOPPED / FAILED bot row stays put so
-- the audit trail is preserved.
--
-- Inventory columns use numeric(38, 0) because:
--   * base / quote balances can exceed 1e18 (e.g. USDT with 6
--     decimals scaled up, or high-value quotes like BTC)
--   * shopspring/decimal is what the rest of the codebase uses
--     and serialises/decodes to numeric cleanly.
--
-- The bot table is intentionally separate from withdrawals /
-- deposits: it tracks the bot's own inventory, not user balances.
-- When a bot stops, the engine returns inventory to the treasury
-- wallet (recorded as a treasury debit on the platform ledger,
-- not as a withdrawal).
CREATE TABLE mmbot_bots (
  -- Stable id, server-generated. Format: "<BASE>_<QUOTE>_mm_<n>".
  bot_id        TEXT PRIMARY KEY,

  -- Trading pair in BASE_QUOTE form. Must match an enabled
  -- entry in config.yaml chainwatcher.pairs at start time.
  pair          TEXT NOT NULL,

  -- Lifecycle. Valid values: STOPPED, SEEDING, READY,
  -- RUNNING, STOPPING, FAILED. The CHECK below enforces.
  status        TEXT NOT NULL CHECK (status IN (
                    'STOPPED', 'SEEDING', 'READY',
                    'RUNNING', 'STOPPING', 'FAILED')),

  -- The mid price the admin specified at Start time. Stored as
  -- numeric so the engine can quote bid/ask = mid +/- half_spread
  -- without round-tripping through float.
  mid_price     NUMERIC(38, 0) NOT NULL,

  -- Half-spread in basis points. Default 10 (0.10% each side).
  spread_bps    INTEGER NOT NULL DEFAULT 10 CHECK (spread_bps >= 1),

  -- === inventory (snapshot, updated by the engine) ===
  -- Base token balance (e.g. BNB).
  base_balance  NUMERIC(38, 0) NOT NULL DEFAULT 0,
  -- Quote token balance (e.g. USDT).
  quote_balance NUMERIC(38, 0) NOT NULL DEFAULT 0,

  -- === outstanding CLOB orders (snapshot, jsonb for flexibility) ===
  -- List of {order_id, side, price, qty} entries that the bot
  -- currently has resting on the CLOB. The engine rewrites this
  -- column whenever it places or cancels a quote. Stored as JSON
  -- so we don't need a child table for the MVP.
  open_orders   JSONB NOT NULL DEFAULT '[]'::JSONB,

  -- === P&L (since this row's created_at) ===
  -- Realised + unrealised P&L expressed in quote units (USDT).
  -- Sign: positive = bot made money, negative = loss. Stored as
  -- numeric so the admin dashboard can format it without float.
  pnl_quote     NUMERIC(38, 0) NOT NULL DEFAULT 0,

  -- === treasury wallet that seeded this bot ===
  -- Optional override; default is the platform treasury from
  -- server config. Recorded here so the audit log is self-
  -- contained even if config changes.
  treasury_wallet TEXT,

  -- bot_wallet: the on-chain wallet the bot owns for this run.
  -- Generated by core, persisted here for admin visibility.
  -- Private key never leaves core.
  bot_wallet    TEXT,

  -- === timestamps ===
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at    TIMESTAMPTZ,
  stopped_at    TIMESTAMPTZ,

  -- last_error populated only when status = FAILED.
  last_error    TEXT
);

-- Only one live bot per pair at any time. A live bot is one of
-- SEEDING, READY, RUNNING, or STOPPING. STOPPED and FAILED rows
-- stay in place so admins can see history.
CREATE UNIQUE INDEX idx_mmbot_pair_live
  ON mmbot_bots (pair)
  WHERE status IN ('SEEDING', 'READY', 'RUNNING', 'STOPPING');

-- Common admin-dashboard query: list bots by status.
CREATE INDEX idx_mmbot_status ON mmbot_bots (status);

-- Common admin-dashboard query: list bots by pair (history).
CREATE INDEX idx_mmbot_pair ON mmbot_bots (pair);

-- === fills audit log ===
--
-- One row per fill the bot receives. Written by core after each
-- matching-engine fill event. The MVP only needs this for P&L
-- audit and for the admin dashboard's recent-trades view; we
-- could later move to a partitioned table by month if volume
-- grows.
CREATE TABLE mmbot_fills (
  -- Auto-incremented primary key. We use bigserial because the
  -- fill rate is unbounded and we want to avoid UUID churn on
  -- the hot write path.
  id              BIGSERIAL PRIMARY KEY,

  bot_id          TEXT NOT NULL REFERENCES mmbot_bots(bot_id)
                    ON DELETE CASCADE,

  -- CLOB-side order id for cross-reference.
  order_id        TEXT NOT NULL,

  -- Side the bot took: 'BUY' (bot bought) or 'SELL' (bot sold).
  -- CHECK because the matching engine emits 'BUY'/'SELL' and
  -- we want typos caught at the DB layer.
  side            TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),

  -- Fill price in quote-per-base. Decimal for consistency
  -- with mmbot_bots.mid_price.
  price           NUMERIC(38, 0) NOT NULL,

  -- Fill quantity in base units. Decimal.
  qty             NUMERIC(38, 0) NOT NULL,

  -- Counterparty: the user order id that filled against us.
  -- Used by the admin dashboard to drill into "who ate my
  -- bot's quote". Nullable because the matching engine sometimes
  -- only reports the order id, not the counterparty id.
  counterparty_id TEXT,

  -- P&L delta from this fill, in quote units. Signed: positive
  -- means the bot earned the spread on this fill (it bought
  -- below mid or sold above mid), negative means it took a
  -- loss (crossed the spread). The engine computes this at
  -- fill time using the bot's mid_price at start.
  pnl_quote_delta NUMERIC(38, 0) NOT NULL,

  -- When the matching engine reported the fill. Used for
  -- audit log ordering and to compute 24h rolling P&L.
  filled_at       TIMESTAMPTZ NOT NULL
);

-- Most common query: "show me the fills for this bot, newest
-- first". The dashboard's recent-trades widget hits this.
CREATE INDEX idx_mmbot_fills_bot ON mmbot_fills (bot_id, filled_at DESC);

-- "Show me all fills across all bots in the last hour" for
-- global P&L monitoring. Brin is cheap on append-only time-
-- series data.
CREATE INDEX idx_mmbot_fills_time ON mmbot_fills USING BRIN (filled_at);

COMMENT ON TABLE  mmbot_bots  IS 'Per-pair market-making bot lifecycle + inventory + P&L snapshot';
COMMENT ON TABLE  mmbot_fills IS 'Append-only audit log of every fill the bot received';
COMMENT ON COLUMN mmbot_bots.bot_wallet IS 'On-chain wallet owned by this bot run. Private key never leaves core.';
COMMENT ON COLUMN mmbot_bots.bot_id     IS 'Stable id in <BASE>_<QUOTE>_mm_<n> form. Server-generated.';
COMMENT ON COLUMN mmbot_bots.open_orders IS 'JSON array of {order_id, side, price, qty}. Engine rewrites on place/cancel.';
