// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mmbot.proto

package mmbotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotStatus int32

const (
	BotStatus_BOT_STATUS_UNSPECIFIED BotStatus = 0
	BotStatus_BOT_STATUS_STOPPED     BotStatus = 1
	BotStatus_BOT_STATUS_SEEDING     BotStatus = 2
	BotStatus_BOT_STATUS_READY       BotStatus = 3
	BotStatus_BOT_STATUS_RUNNING     BotStatus = 4
	BotStatus_BOT_STATUS_STOPPING    BotStatus = 5
	BotStatus_BOT_STATUS_FAILED      BotStatus = 6
)

// Enum value maps for BotStatus.
var (
	BotStatus_name = map[int32]string{
		0: "BOT_STATUS_UNSPECIFIED",
		1: "BOT_STATUS_STOPPED",
		2: "BOT_STATUS_SEEDING",
		3: "BOT_STATUS_READY",
		4: "BOT_STATUS_RUNNING",
		5: "BOT_STATUS_STOPPING",
		6: "BOT_STATUS_FAILED",
	}
	BotStatus_value = map[string]int32{
		"BOT_STATUS_UNSPECIFIED": 0,
		"BOT_STATUS_STOPPED":     1,
		"BOT_STATUS_SEEDING":     2,
		"BOT_STATUS_READY":       3,
		"BOT_STATUS_RUNNING":     4,
		"BOT_STATUS_STOPPING":    5,
		"BOT_STATUS_FAILED":      6,
	}
)

func (x BotStatus) Enum() *BotStatus {
	p := new(BotStatus)
	*p = x
	return p
}

func (x BotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mmbot_proto_enumTypes[0].Descriptor()
}

func (BotStatus) Type() protoreflect.EnumType {
	return &file_mmbot_proto_enumTypes[0]
}

func (x BotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotStatus.Descriptor instead.
func (BotStatus) EnumDescriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{0}
}

type AdminTickEvent_Kind int32

const (
	AdminTickEvent_KIND_UNSPECIFIED    AdminTickEvent_Kind = 0
	AdminTickEvent_KIND_ORDER_FILLED   AdminTickEvent_Kind = 1
	AdminTickEvent_KIND_INVENTORY_SKEW AdminTickEvent_Kind = 2
	AdminTickEvent_KIND_REBALANCED     AdminTickEvent_Kind = 3
	AdminTickEvent_KIND_HEARTBEAT      AdminTickEvent_Kind = 4
)

// Enum value maps for AdminTickEvent_Kind.
var (
	AdminTickEvent_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_ORDER_FILLED",
		2: "KIND_INVENTORY_SKEW",
		3: "KIND_REBALANCED",
		4: "KIND_HEARTBEAT",
	}
	AdminTickEvent_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":    0,
		"KIND_ORDER_FILLED":   1,
		"KIND_INVENTORY_SKEW": 2,
		"KIND_REBALANCED":     3,
		"KIND_HEARTBEAT":      4,
	}
)

func (x AdminTickEvent_Kind) Enum() *AdminTickEvent_Kind {
	p := new(AdminTickEvent_Kind)
	*p = x
	return p
}

func (x AdminTickEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminTickEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_mmbot_proto_enumTypes[1].Descriptor()
}

func (AdminTickEvent_Kind) Type() protoreflect.EnumType {
	return &file_mmbot_proto_enumTypes[1]
}

func (x AdminTickEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminTickEvent_Kind.Descriptor instead.
func (AdminTickEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{10, 0}
}

type BotState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Pair          string                 `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Status        BotStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=mmbot.v1.BotStatus" json:"status,omitempty"`
	MidPrice      string                 `protobuf:"bytes,4,opt,name=mid_price,json=midPrice,proto3" json:"mid_price,omitempty"`
	SpreadBps     int32                  `protobuf:"varint,5,opt,name=spread_bps,json=spreadBps,proto3" json:"spread_bps,omitempty"`
	BaseBalance   string                 `protobuf:"bytes,6,opt,name=base_balance,json=baseBalance,proto3" json:"base_balance,omitempty"`
	QuoteBalance  string                 `protobuf:"bytes,7,opt,name=quote_balance,json=quoteBalance,proto3" json:"quote_balance,omitempty"`
	OpenOrderIds  []string               `protobuf:"bytes,8,rep,name=open_order_ids,json=openOrderIds,proto3" json:"open_order_ids,omitempty"`
	PnlQuote      string                 `protobuf:"bytes,9,opt,name=pnl_quote,json=pnlQuote,proto3" json:"pnl_quote,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StoppedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	LastError     string                 `protobuf:"bytes,13,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotState) Reset() {
	*x = BotState{}
	mi := &file_mmbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotState) ProtoMessage() {}

func (x *BotState) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotState.ProtoReflect.Descriptor instead.
func (*BotState) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{0}
}

func (x *BotState) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *BotState) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *BotState) GetStatus() BotStatus {
	if x != nil {
		return x.Status
	}
	return BotStatus_BOT_STATUS_UNSPECIFIED
}

func (x *BotState) GetMidPrice() string {
	if x != nil {
		return x.MidPrice
	}
	return ""
}

func (x *BotState) GetSpreadBps() int32 {
	if x != nil {
		return x.SpreadBps
	}
	return 0
}

func (x *BotState) GetBaseBalance() string {
	if x != nil {
		return x.BaseBalance
	}
	return ""
}

func (x *BotState) GetQuoteBalance() string {
	if x != nil {
		return x.QuoteBalance
	}
	return ""
}

func (x *BotState) GetOpenOrderIds() []string {
	if x != nil {
		return x.OpenOrderIds
	}
	return nil
}

func (x *BotState) GetPnlQuote() string {
	if x != nil {
		return x.PnlQuote
	}
	return ""
}

func (x *BotState) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BotState) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *BotState) GetStoppedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StoppedAt
	}
	return nil
}

func (x *BotState) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type StartRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pair            string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	MidPrice        string                 `protobuf:"bytes,2,opt,name=mid_price,json=midPrice,proto3" json:"mid_price,omitempty"`
	QuoteSeed       string                 `protobuf:"bytes,3,opt,name=quote_seed,json=quoteSeed,proto3" json:"quote_seed,omitempty"`
	BaseSeed        string                 `protobuf:"bytes,4,opt,name=base_seed,json=baseSeed,proto3" json:"base_seed,omitempty"`
	SpreadBps       int32                  `protobuf:"varint,5,opt,name=spread_bps,json=spreadBps,proto3" json:"spread_bps,omitempty"`
	TreasuryWallet  string                 `protobuf:"bytes,6,opt,name=treasury_wallet,json=treasuryWallet,proto3" json:"treasury_wallet,omitempty"`
	MinQuotePerSide string                 `protobuf:"bytes,7,opt,name=min_quote_per_side,json=minQuotePerSide,proto3" json:"min_quote_per_side,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_mmbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *StartRequest) GetMidPrice() string {
	if x != nil {
		return x.MidPrice
	}
	return ""
}

func (x *StartRequest) GetQuoteSeed() string {
	if x != nil {
		return x.QuoteSeed
	}
	return ""
}

func (x *StartRequest) GetBaseSeed() string {
	if x != nil {
		return x.BaseSeed
	}
	return ""
}

func (x *StartRequest) GetSpreadBps() int32 {
	if x != nil {
		return x.SpreadBps
	}
	return 0
}

func (x *StartRequest) GetTreasuryWallet() string {
	if x != nil {
		return x.TreasuryWallet
	}
	return ""
}

func (x *StartRequest) GetMinQuotePerSide() string {
	if x != nil {
		return x.MinQuotePerSide
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           *BotState              `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_mmbot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{2}
}

func (x *StartResponse) GetBot() *BotState {
	if x != nil {
		return x.Bot
	}
	return nil
}

type StopRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BotId           string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ReturnInventory bool                   `protobuf:"varint,2,opt,name=return_inventory,json=returnInventory,proto3" json:"return_inventory,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_mmbot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{3}
}

func (x *StopRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *StopRequest) GetReturnInventory() bool {
	if x != nil {
		return x.ReturnInventory
	}
	return false
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           *BotState              `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	ReturnedQuote string                 `protobuf:"bytes,2,opt,name=returned_quote,json=returnedQuote,proto3" json:"returned_quote,omitempty"`
	ReturnedBase  string                 `protobuf:"bytes,3,opt,name=returned_base,json=returnedBase,proto3" json:"returned_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_mmbot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{4}
}

func (x *StopResponse) GetBot() *BotState {
	if x != nil {
		return x.Bot
	}
	return nil
}

func (x *StopResponse) GetReturnedQuote() string {
	if x != nil {
		return x.ReturnedQuote
	}
	return ""
}

func (x *StopResponse) GetReturnedBase() string {
	if x != nil {
		return x.ReturnedBase
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_mmbot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           *BotState              `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_mmbot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetBot() *BotState {
	if x != nil {
		return x.Bot
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairFilter    string                 `protobuf:"bytes,1,opt,name=pair_filter,json=pairFilter,proto3" json:"pair_filter,omitempty"`
	StatusFilter  BotStatus              `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=mmbot.v1.BotStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_mmbot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{7}
}

func (x *ListRequest) GetPairFilter() string {
	if x != nil {
		return x.PairFilter
	}
	return ""
}

func (x *ListRequest) GetStatusFilter() BotStatus {
	if x != nil {
		return x.StatusFilter
	}
	return BotStatus_BOT_STATUS_UNSPECIFIED
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bots          []*BotState            `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_mmbot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponse) GetBots() []*BotState {
	if x != nil {
		return x.Bots
	}
	return nil
}

type AdminTickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminTickRequest) Reset() {
	*x = AdminTickRequest{}
	mi := &file_mmbot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTickRequest) ProtoMessage() {}

func (x *AdminTickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTickRequest.ProtoReflect.Descriptor instead.
func (*AdminTickRequest) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{9}
}

func (x *AdminTickRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type AdminTickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AdminTickEvent_Kind    `protobuf:"varint,1,opt,name=kind,proto3,enum=mmbot.v1.AdminTickEvent_Kind" json:"kind,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminTickEvent) Reset() {
	*x = AdminTickEvent{}
	mi := &file_mmbot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTickEvent) ProtoMessage() {}

func (x *AdminTickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mmbot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTickEvent.ProtoReflect.Descriptor instead.
func (*AdminTickEvent) Descriptor() ([]byte, []int) {
	return file_mmbot_proto_rawDescGZIP(), []int{10}
}

func (x *AdminTickEvent) GetKind() AdminTickEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return AdminTickEvent_KIND_UNSPECIFIED
}

func (x *AdminTickEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *AdminTickEvent) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_mmbot_proto protoreflect.FileDescriptor

const file_mmbot_proto_rawDesc = "" +
	"\n" +
	"\vmmbot.proto\x12\bmmbot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x03\n" +
	"\bBotState\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.mmbot.v1.BotStatusR\x06status\x12\x1b\n" +
	"\tmid_price\x18\x04 \x01(\tR\bmidPrice\x12\x1d\n" +
	"\n" +
	"spread_bps\x18\x05 \x01(\x05R\tspreadBps\x12!\n" +
	"\fbase_balance\x18\x06 \x01(\tR\vbaseBalance\x12#\n" +
	"\rquote_balance\x18\a \x01(\tR\fquoteBalance\x12$\n" +
	"\x0eopen_order_ids\x18\b \x03(\tR\fopenOrderIds\x12\x1b\n" +
	"\tpnl_quote\x18\t \x01(\tR\bpnlQuote\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"stopped_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstoppedAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\r \x01(\tR\tlastError\"\xf0\x01\n" +
	"\fStartRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x1b\n" +
	"\tmid_price\x18\x02 \x01(\tR\bmidPrice\x12\x1d\n" +
	"\n" +
	"quote_seed\x18\x03 \x01(\tR\tquoteSeed\x12\x1b\n" +
	"\tbase_seed\x18\x04 \x01(\tR\bbaseSeed\x12\x1d\n" +
	"\n" +
	"spread_bps\x18\x05 \x01(\x05R\tspreadBps\x12'\n" +
	"\x0ftreasury_wallet\x18\x06 \x01(\tR\x0etreasuryWallet\x12+\n" +
	"\x12min_quote_per_side\x18\a \x01(\tR\x0fminQuotePerSide\"5\n" +
	"\rStartResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.mmbot.v1.BotStateR\x03bot\"O\n" +
	"\vStopRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12)\n" +
	"\x10return_inventory\x18\x02 \x01(\bR\x0freturnInventory\"\x80\x01\n" +
	"\fStopResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.mmbot.v1.BotStateR\x03bot\x12%\n" +
	"\x0ereturned_quote\x18\x02 \x01(\tR\rreturnedQuote\x12#\n" +
	"\rreturned_base\x18\x03 \x01(\tR\freturnedBase\"&\n" +
	"\rStatusRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"6\n" +
	"\x0eStatusResponse\x12$\n" +
	"\x03bot\x18\x01 \x01(\v2\x12.mmbot.v1.BotStateR\x03bot\"h\n" +
	"\vListRequest\x12\x1f\n" +
	"\vpair_filter\x18\x01 \x01(\tR\n" +
	"pairFilter\x128\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x13.mmbot.v1.BotStatusR\fstatusFilter\"6\n" +
	"\fListResponse\x12&\n" +
	"\x04bots\x18\x01 \x03(\v2\x12.mmbot.v1.BotStateR\x04bots\")\n" +
	"\x10AdminTickRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"\xfa\x01\n" +
	"\x0eAdminTickEvent\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.mmbot.v1.AdminTickEvent.KindR\x04kind\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"u\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11KIND_ORDER_FILLED\x10\x01\x12\x17\n" +
	"\x13KIND_INVENTORY_SKEW\x10\x02\x12\x13\n" +
	"\x0fKIND_REBALANCED\x10\x03\x12\x12\n" +
	"\x0eKIND_HEARTBEAT\x10\x04*\xb5\x01\n" +
	"\tBotStatus\x12\x1a\n" +
	"\x16BOT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BOT_STATUS_STOPPED\x10\x01\x12\x16\n" +
	"\x12BOT_STATUS_SEEDING\x10\x02\x12\x14\n" +
	"\x10BOT_STATUS_READY\x10\x03\x12\x16\n" +
	"\x12BOT_STATUS_RUNNING\x10\x04\x12\x17\n" +
	"\x13BOT_STATUS_STOPPING\x10\x05\x12\x15\n" +
	"\x11BOT_STATUS_FAILED\x10\x062\xb8\x02\n" +
	"\fMMBotService\x128\n" +
	"\x05Start\x12\x16.mmbot.v1.StartRequest\x1a\x17.mmbot.v1.StartResponse\x125\n" +
	"\x04Stop\x12\x15.mmbot.v1.StopRequest\x1a\x16.mmbot.v1.StopResponse\x12;\n" +
	"\x06Status\x12\x17.mmbot.v1.StatusRequest\x1a\x18.mmbot.v1.StatusResponse\x125\n" +
	"\x04List\x12\x15.mmbot.v1.ListRequest\x1a\x16.mmbot.v1.ListResponse\x12C\n" +
	"\tAdminTick\x12\x1a.mmbot.v1.AdminTickRequest\x1a\x18.mmbot.v1.AdminTickEvent0\x01B6Z4github.com/goexdev/goexchange/internal/mmbot/mmbotv1b\x06proto3"

var (
	file_mmbot_proto_rawDescOnce sync.Once
	file_mmbot_proto_rawDescData []byte
)

func file_mmbot_proto_rawDescGZIP() []byte {
	file_mmbot_proto_rawDescOnce.Do(func() {
		file_mmbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mmbot_proto_rawDesc), len(file_mmbot_proto_rawDesc)))
	})
	return file_mmbot_proto_rawDescData
}

var file_mmbot_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mmbot_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mmbot_proto_goTypes = []any{
	(BotStatus)(0),                // 0: mmbot.v1.BotStatus
	(AdminTickEvent_Kind)(0),      // 1: mmbot.v1.AdminTickEvent.Kind
	(*BotState)(nil),              // 2: mmbot.v1.BotState
	(*StartRequest)(nil),          // 3: mmbot.v1.StartRequest
	(*StartResponse)(nil),         // 4: mmbot.v1.StartResponse
	(*StopRequest)(nil),           // 5: mmbot.v1.StopRequest
	(*StopResponse)(nil),          // 6: mmbot.v1.StopResponse
	(*StatusRequest)(nil),         // 7: mmbot.v1.StatusRequest
	(*StatusResponse)(nil),        // 8: mmbot.v1.StatusResponse
	(*ListRequest)(nil),           // 9: mmbot.v1.ListRequest
	(*ListResponse)(nil),          // 10: mmbot.v1.ListResponse
	(*AdminTickRequest)(nil),      // 11: mmbot.v1.AdminTickRequest
	(*AdminTickEvent)(nil),        // 12: mmbot.v1.AdminTickEvent
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_mmbot_proto_depIdxs = []int32{
	0,  // 0: mmbot.v1.BotState.status:type_name -> mmbot.v1.BotStatus
	13, // 1: mmbot.v1.BotState.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: mmbot.v1.BotState.started_at:type_name -> google.protobuf.Timestamp
	13, // 3: mmbot.v1.BotState.stopped_at:type_name -> google.protobuf.Timestamp
	2,  // 4: mmbot.v1.StartResponse.bot:type_name -> mmbot.v1.BotState
	2,  // 5: mmbot.v1.StopResponse.bot:type_name -> mmbot.v1.BotState
	2,  // 6: mmbot.v1.StatusResponse.bot:type_name -> mmbot.v1.BotState
	0,  // 7: mmbot.v1.ListRequest.status_filter:type_name -> mmbot.v1.BotStatus
	2,  // 8: mmbot.v1.ListResponse.bots:type_name -> mmbot.v1.BotState
	1,  // 9: mmbot.v1.AdminTickEvent.kind:type_name -> mmbot.v1.AdminTickEvent.Kind
	13, // 10: mmbot.v1.AdminTickEvent.at:type_name -> google.protobuf.Timestamp
	3,  // 11: mmbot.v1.MMBotService.Start:input_type -> mmbot.v1.StartRequest
	5,  // 12: mmbot.v1.MMBotService.Stop:input_type -> mmbot.v1.StopRequest
	7,  // 13: mmbot.v1.MMBotService.Status:input_type -> mmbot.v1.StatusRequest
	9,  // 14: mmbot.v1.MMBotService.List:input_type -> mmbot.v1.ListRequest
	11, // 15: mmbot.v1.MMBotService.AdminTick:input_type -> mmbot.v1.AdminTickRequest
	4,  // 16: mmbot.v1.MMBotService.Start:output_type -> mmbot.v1.StartResponse
	6,  // 17: mmbot.v1.MMBotService.Stop:output_type -> mmbot.v1.StopResponse
	8,  // 18: mmbot.v1.MMBotService.Status:output_type -> mmbot.v1.StatusResponse
	10, // 19: mmbot.v1.MMBotService.List:output_type -> mmbot.v1.ListResponse
	12, // 20: mmbot.v1.MMBotService.AdminTick:output_type -> mmbot.v1.AdminTickEvent
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_mmbot_proto_init() }
func file_mmbot_proto_init() {
	if File_mmbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mmbot_proto_rawDesc), len(file_mmbot_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mmbot_proto_goTypes,
		DependencyIndexes: file_mmbot_proto_depIdxs,
		EnumInfos:         file_mmbot_proto_enumTypes,
		MessageInfos:      file_mmbot_proto_msgTypes,
	}.Build()
	File_mmbot_proto = out.File
	file_mmbot_proto_goTypes = nil
	file_mmbot_proto_depIdxs = nil
}
