// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: mmbot.proto

package mmbotv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MMBotService_Start_FullMethodName     = "/mmbot.v1.MMBotService/Start"
	MMBotService_Stop_FullMethodName      = "/mmbot.v1.MMBotService/Stop"
	MMBotService_Status_FullMethodName    = "/mmbot.v1.MMBotService/Status"
	MMBotService_List_FullMethodName      = "/mmbot.v1.MMBotService/List"
	MMBotService_AdminTick_FullMethodName = "/mmbot.v1.MMBotService/AdminTick"
)

// MMBotServiceClient is the client API for MMBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MMBotService is the gRPC interface between the public API server
// and the proprietary per-pair market-making bot. The public
// repository owns the .proto file; the bot engine generates stubs
// from it during build.
//
// One bot instance exists per configured trading pair (e.g.
// BNB_USDT, ETH_USDT). Bots are admin-controlled: the admin
// seeds inventory, starts/stops the run loop, and the bot quotes
// bid/ask around the configured mid price using the existing
// CLOB matching engine (separate gRPC service).
type MMBotServiceClient interface {
	// Start launches a new bot run for the given pair. The bot
	// engine creates a bot_wallet (private key persisted in
	// core, never returned in this RPC), seeds inventory from the
	// treasury wallet, and begins quoting on the CLOB.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Stop halts a running bot: cancel all open orders, return
	// remaining inventory to the treasury, compute P&L, and
	// persist a final state row. Idempotent — returns the current
	// state if the bot is already STOPPED.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Status returns a snapshot of one bot's current state, including
	// inventory, outstanding orders, and realised + unrealised P&L.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// List returns all bots (one row per pair). Used by admin
	// dashboards to show which pairs have an active bot.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// AdminTick is a server-streaming RPC the public API uses to
	// push operator commands (cancel all, raise spread, withdraw)
	// into a running bot without restarting it. Currently unused;
	// reserved for future emergency-kill features.
	AdminTick(ctx context.Context, in *AdminTickRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AdminTickEvent], error)
}

type mMBotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMMBotServiceClient(cc grpc.ClientConnInterface) MMBotServiceClient {
	return &mMBotServiceClient{cc}
}

func (c *mMBotServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, MMBotService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mMBotServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, MMBotService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mMBotServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MMBotService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mMBotServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, MMBotService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mMBotServiceClient) AdminTick(ctx context.Context, in *AdminTickRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AdminTickEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MMBotService_ServiceDesc.Streams[0], MMBotService_AdminTick_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AdminTickRequest, AdminTickEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MMBotService_AdminTickClient = grpc.ServerStreamingClient[AdminTickEvent]

// MMBotServiceServer is the server API for MMBotService service.
// All implementations must embed UnimplementedMMBotServiceServer
// for forward compatibility.
//
// MMBotService is the gRPC interface between the public API server
// and the proprietary per-pair market-making bot. The public
// repository owns the .proto file; the bot engine generates stubs
// from it during build.
//
// One bot instance exists per configured trading pair (e.g.
// BNB_USDT, ETH_USDT). Bots are admin-controlled: the admin
// seeds inventory, starts/stops the run loop, and the bot quotes
// bid/ask around the configured mid price using the existing
// CLOB matching engine (separate gRPC service).
type MMBotServiceServer interface {
	// Start launches a new bot run for the given pair. The bot
	// engine creates a bot_wallet (private key persisted in
	// core, never returned in this RPC), seeds inventory from the
	// treasury wallet, and begins quoting on the CLOB.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Stop halts a running bot: cancel all open orders, return
	// remaining inventory to the treasury, compute P&L, and
	// persist a final state row. Idempotent — returns the current
	// state if the bot is already STOPPED.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Status returns a snapshot of one bot's current state, including
	// inventory, outstanding orders, and realised + unrealised P&L.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// List returns all bots (one row per pair). Used by admin
	// dashboards to show which pairs have an active bot.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// AdminTick is a server-streaming RPC the public API uses to
	// push operator commands (cancel all, raise spread, withdraw)
	// into a running bot without restarting it. Currently unused;
	// reserved for future emergency-kill features.
	AdminTick(*AdminTickRequest, grpc.ServerStreamingServer[AdminTickEvent]) error
	mustEmbedUnimplementedMMBotServiceServer()
}

// UnimplementedMMBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMMBotServiceServer struct{}

func (UnimplementedMMBotServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedMMBotServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedMMBotServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMMBotServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedMMBotServiceServer) AdminTick(*AdminTickRequest, grpc.ServerStreamingServer[AdminTickEvent]) error {
	return status.Error(codes.Unimplemented, "method AdminTick not implemented")
}
func (UnimplementedMMBotServiceServer) mustEmbedUnimplementedMMBotServiceServer() {}
func (UnimplementedMMBotServiceServer) testEmbeddedByValue()                      {}

// UnsafeMMBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MMBotServiceServer will
// result in compilation errors.
type UnsafeMMBotServiceServer interface {
	mustEmbedUnimplementedMMBotServiceServer()
}

func RegisterMMBotServiceServer(s grpc.ServiceRegistrar, srv MMBotServiceServer) {
	// If the following call panics, it indicates UnimplementedMMBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MMBotService_ServiceDesc, srv)
}

func _MMBotService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MMBotServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MMBotService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MMBotServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MMBotService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MMBotServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MMBotService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MMBotServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MMBotService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MMBotServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MMBotService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MMBotServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MMBotService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MMBotServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MMBotService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MMBotServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MMBotService_AdminTick_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AdminTickRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MMBotServiceServer).AdminTick(m, &grpc.GenericServerStream[AdminTickRequest, AdminTickEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MMBotService_AdminTickServer = grpc.ServerStreamingServer[AdminTickEvent]

// MMBotService_ServiceDesc is the grpc.ServiceDesc for MMBotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MMBotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mmbot.v1.MMBotService",
	HandlerType: (*MMBotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _MMBotService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _MMBotService_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _MMBotService_Status_Handler,
		},
		{
			MethodName: "List",
			Handler:    _MMBotService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AdminTick",
			Handler:       _MMBotService_AdminTick_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mmbot.proto",
}
