// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pkg/grpcpkg/signer.proto

package signerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignerService_SignTransaction_FullMethodName = "/signer.v1.SignerService/SignTransaction"
	SignerService_DeriveAddress_FullMethodName   = "/signer.v1.SignerService/DeriveAddress"
	SignerService_Health_FullMethodName          = "/signer.v1.SignerService/Health"
)

// SignerServiceClient is the client API for SignerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SignerService is the closed-source signing daemon used by the
// public-repository wallet service. The signer runs in a separate
// process and inside a private Docker network so it can pull secrets
// from Vault without exposing private-key material to anything
// outside the daemon.
//
// The public repository owns this .proto definition (the matching
// service follows the same pattern); the daemon generates stubs from
// it during the core-repo release build.
type SignerServiceClient interface {
	// SignTransaction signs an unsigned transaction payload and returns
	// the serialized signed bytes. The caller passes the chain
	// identifier ("TRON", "BTC", "ETH", ...) so the daemon can pick
	// the right signing algorithm and chain-id byte.
	SignTransaction(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	// DeriveAddress derives the next BIP-44 address for the given
	// chain. Used by AllocateDepositAddress in the wallet service to
	// mint a fresh deposit address without ever exposing the mnemonic
	// to the public process.
	DeriveAddress(ctx context.Context, in *DeriveRequest, opts ...grpc.CallOption) (*DeriveResponse, error)
	// Health reports whether the daemon is ready to handle requests
	// (vault unsealed, hot wallet loaded, etc.).
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type signerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerServiceClient(cc grpc.ClientConnInterface) SignerServiceClient {
	return &signerServiceClient{cc}
}

func (c *signerServiceClient) SignTransaction(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, SignerService_SignTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) DeriveAddress(ctx context.Context, in *DeriveRequest, opts ...grpc.CallOption) (*DeriveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeriveResponse)
	err := c.cc.Invoke(ctx, SignerService_DeriveAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SignerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServiceServer is the server API for SignerService service.
// All implementations must embed UnimplementedSignerServiceServer
// for forward compatibility.
//
// SignerService is the closed-source signing daemon used by the
// public-repository wallet service. The signer runs in a separate
// process and inside a private Docker network so it can pull secrets
// from Vault without exposing private-key material to anything
// outside the daemon.
//
// The public repository owns this .proto definition (the matching
// service follows the same pattern); the daemon generates stubs from
// it during the core-repo release build.
type SignerServiceServer interface {
	// SignTransaction signs an unsigned transaction payload and returns
	// the serialized signed bytes. The caller passes the chain
	// identifier ("TRON", "BTC", "ETH", ...) so the daemon can pick
	// the right signing algorithm and chain-id byte.
	SignTransaction(context.Context, *SignRequest) (*SignResponse, error)
	// DeriveAddress derives the next BIP-44 address for the given
	// chain. Used by AllocateDepositAddress in the wallet service to
	// mint a fresh deposit address without ever exposing the mnemonic
	// to the public process.
	DeriveAddress(context.Context, *DeriveRequest) (*DeriveResponse, error)
	// Health reports whether the daemon is ready to handle requests
	// (vault unsealed, hot wallet loaded, etc.).
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSignerServiceServer()
}

// UnimplementedSignerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignerServiceServer struct{}

func (UnimplementedSignerServiceServer) SignTransaction(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignTransaction not implemented")
}
func (UnimplementedSignerServiceServer) DeriveAddress(context.Context, *DeriveRequest) (*DeriveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeriveAddress not implemented")
}
func (UnimplementedSignerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSignerServiceServer) mustEmbedUnimplementedSignerServiceServer() {}
func (UnimplementedSignerServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignerServiceServer will
// result in compilation errors.
type UnsafeSignerServiceServer interface {
	mustEmbedUnimplementedSignerServiceServer()
}

func RegisterSignerServiceServer(s grpc.ServiceRegistrar, srv SignerServiceServer) {
	// If the following call panics, it indicates UnimplementedSignerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignerService_ServiceDesc, srv)
}

func _SignerService_SignTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).SignTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_SignTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).SignTransaction(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_DeriveAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).DeriveAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_DeriveAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).DeriveAddress(ctx, req.(*DeriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignerService_ServiceDesc is the grpc.ServiceDesc for SignerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signer.v1.SignerService",
	HandlerType: (*SignerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignTransaction",
			Handler:    _SignerService_SignTransaction_Handler,
		},
		{
			MethodName: "DeriveAddress",
			Handler:    _SignerService_DeriveAddress_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SignerService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpcpkg/signer.proto",
}
