// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/grpcpkg/signer.proto

package signerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignRequest asks the daemon to sign a raw transaction.
//
// raw_tx is the chain-native serialisation of the transaction in
// its unsigned form (TRON: TriggerSmartContract protobuf; BTC: PSBT;
// ETH: RLP-encoded legacy). key_id selects which signer key to use
// (e.g. "hot_wallet" or "cold_wallet"). network disambiguates
// mainnet vs testnet (e.g. "mainnet" vs "nile_testnet" for TRON).
type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	RawTx         []byte                 `protobuf:"bytes,3,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcpkg_signer_proto_rawDescGZIP(), []int{0}
}

func (x *SignRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *SignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignRequest) GetRawTx() []byte {
	if x != nil {
		return x.RawTx
	}
	return nil
}

func (x *SignRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

// SignResponse is the daemon's reply. signed_tx is the input raw_tx
// with the signature applied; tx_hash is the network-assigned hash
// (TRON: 32-byte keccak; BTC: double-sha256; ETH: keccak of RLP).
// error is empty on success and a short human-readable failure
// reason on failure (e.g. "decrypt: vault sealed").
type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedTx      []byte                 `protobuf:"bytes,1,opt,name=signed_tx,json=signedTx,proto3" json:"signed_tx,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcpkg_signer_proto_rawDescGZIP(), []int{1}
}

func (x *SignResponse) GetSignedTx() []byte {
	if x != nil {
		return x.SignedTx
	}
	return nil
}

func (x *SignResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SignResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DeriveRequest asks the daemon to derive the address at a given
// BIP-44 index. index=0 returns the first derived address (m/44'/X'/0'/0/0).
type DeriveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveRequest) Reset() {
	*x = DeriveRequest{}
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveRequest) ProtoMessage() {}

func (x *DeriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveRequest.ProtoReflect.Descriptor instead.
func (*DeriveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcpkg_signer_proto_rawDescGZIP(), []int{2}
}

func (x *DeriveRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *DeriveRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// DeriveResponse is the daemon's reply. address is the user-facing
// form (TRON Base58Check, EVM 0x..., BTC bech32). address_hex is the
// hex form for indexing. public_key is the hex-encoded compressed
// or uncompressed key depending on chain convention.
type DeriveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AddressHex    string                 `protobuf:"bytes,2,opt,name=address_hex,json=addressHex,proto3" json:"address_hex,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveResponse) Reset() {
	*x = DeriveResponse{}
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveResponse) ProtoMessage() {}

func (x *DeriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveResponse.ProtoReflect.Descriptor instead.
func (*DeriveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcpkg_signer_proto_rawDescGZIP(), []int{3}
}

func (x *DeriveResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeriveResponse) GetAddressHex() string {
	if x != nil {
		return x.AddressHex
	}
	return ""
}

func (x *DeriveResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DeriveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpcpkg_signer_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	VaultStatus   string                 `protobuf:"bytes,2,opt,name=vault_status,json=vaultStatus,proto3" json:"vault_status,omitempty"`
	Chains        []string               `protobuf:"bytes,3,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpcpkg_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpcpkg_signer_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVaultStatus() string {
	if x != nil {
		return x.VaultStatus
	}
	return ""
}

func (x *HealthResponse) GetChains() []string {
	if x != nil {
		return x.Chains
	}
	return nil
}

var File_pkg_grpcpkg_signer_proto protoreflect.FileDescriptor

const file_pkg_grpcpkg_signer_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/grpcpkg/signer.proto\x12\tsigner.v1\"k\n" +
	"\vSignRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x15\n" +
	"\x06raw_tx\x18\x03 \x01(\fR\x05rawTx\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\"Z\n" +
	"\fSignResponse\x12\x1b\n" +
	"\tsigned_tx\x18\x01 \x01(\fR\bsignedTx\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\";\n" +
	"\rDeriveRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\x80\x01\n" +
	"\x0eDeriveResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vaddress_hex\x18\x02 \x01(\tR\n" +
	"addressHex\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"[\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fvault_status\x18\x02 \x01(\tR\vvaultStatus\x12\x16\n" +
	"\x06chains\x18\x03 \x03(\tR\x06chains2\xd8\x01\n" +
	"\rSignerService\x12B\n" +
	"\x0fSignTransaction\x12\x16.signer.v1.SignRequest\x1a\x17.signer.v1.SignResponse\x12D\n" +
	"\rDeriveAddress\x12\x18.signer.v1.DeriveRequest\x1a\x19.signer.v1.DeriveResponse\x12=\n" +
	"\x06Health\x12\x18.signer.v1.HealthRequest\x1a\x19.signer.v1.HealthResponseB9Z7github.com/goexdev/goexchange-core/pkg/grpcpkg/signerv1b\x06proto3"

var (
	file_pkg_grpcpkg_signer_proto_rawDescOnce sync.Once
	file_pkg_grpcpkg_signer_proto_rawDescData []byte
)

func file_pkg_grpcpkg_signer_proto_rawDescGZIP() []byte {
	file_pkg_grpcpkg_signer_proto_rawDescOnce.Do(func() {
		file_pkg_grpcpkg_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpcpkg_signer_proto_rawDesc), len(file_pkg_grpcpkg_signer_proto_rawDesc)))
	})
	return file_pkg_grpcpkg_signer_proto_rawDescData
}

var file_pkg_grpcpkg_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_grpcpkg_signer_proto_goTypes = []any{
	(*SignRequest)(nil),    // 0: signer.v1.SignRequest
	(*SignResponse)(nil),   // 1: signer.v1.SignResponse
	(*DeriveRequest)(nil),  // 2: signer.v1.DeriveRequest
	(*DeriveResponse)(nil), // 3: signer.v1.DeriveResponse
	(*HealthRequest)(nil),  // 4: signer.v1.HealthRequest
	(*HealthResponse)(nil), // 5: signer.v1.HealthResponse
}
var file_pkg_grpcpkg_signer_proto_depIdxs = []int32{
	0, // 0: signer.v1.SignerService.SignTransaction:input_type -> signer.v1.SignRequest
	2, // 1: signer.v1.SignerService.DeriveAddress:input_type -> signer.v1.DeriveRequest
	4, // 2: signer.v1.SignerService.Health:input_type -> signer.v1.HealthRequest
	1, // 3: signer.v1.SignerService.SignTransaction:output_type -> signer.v1.SignResponse
	3, // 4: signer.v1.SignerService.DeriveAddress:output_type -> signer.v1.DeriveResponse
	5, // 5: signer.v1.SignerService.Health:output_type -> signer.v1.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpcpkg_signer_proto_init() }
func file_pkg_grpcpkg_signer_proto_init() {
	if File_pkg_grpcpkg_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpcpkg_signer_proto_rawDesc), len(file_pkg_grpcpkg_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpcpkg_signer_proto_goTypes,
		DependencyIndexes: file_pkg_grpcpkg_signer_proto_depIdxs,
		MessageInfos:      file_pkg_grpcpkg_signer_proto_msgTypes,
	}.Build()
	File_pkg_grpcpkg_signer_proto = out.File
	file_pkg_grpcpkg_signer_proto_goTypes = nil
	file_pkg_grpcpkg_signer_proto_depIdxs = nil
}
