// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/matching.proto

package matchingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_BUY              Side = 1
	Side_SELL             Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "BUY",
		2: "SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"BUY":              1,
		"SELL":             2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matching_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_proto_matching_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_LIMIT                  OrderType = 1
	OrderType_MARKET                 OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "LIMIT",
		2: "MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"LIMIT":                  1,
		"MARKET":                 2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matching_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_proto_matching_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{1}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_OPEN               Status = 1
	Status_PARTIAL            Status = 2
	Status_FILLED             Status = 3
	Status_CANCELED           Status = 4
	Status_REJECTED           Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "OPEN",
		2: "PARTIAL",
		3: "FILLED",
		4: "CANCELED",
		5: "REJECTED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"OPEN":               1,
		"PARTIAL":            2,
		"FILLED":             3,
		"CANCELED":           4,
		"REJECTED":           5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matching_proto_enumTypes[2].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_matching_proto_enumTypes[2]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{2}
}

type TimeInForce int32

const (
	TimeInForce_TIF_UNSPECIFIED TimeInForce = 0
	TimeInForce_GTC             TimeInForce = 1
	TimeInForce_IOC             TimeInForce = 2
	TimeInForce_FOK             TimeInForce = 3
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIF_UNSPECIFIED",
		1: "GTC",
		2: "IOC",
		3: "FOK",
	}
	TimeInForce_value = map[string]int32{
		"TIF_UNSPECIFIED": 0,
		"GTC":             1,
		"IOC":             2,
		"FOK":             3,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matching_proto_enumTypes[3].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_proto_matching_proto_enumTypes[3]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{3}
}

type STPMode int32

const (
	STPMode_STP_UNSPECIFIED STPMode = 0
	STPMode_NONE            STPMode = 1
	STPMode_CANCEL_TAKER    STPMode = 2
	STPMode_CANCEL_MAKER    STPMode = 3
	STPMode_CANCEL_BOTH     STPMode = 4
)

// Enum value maps for STPMode.
var (
	STPMode_name = map[int32]string{
		0: "STP_UNSPECIFIED",
		1: "NONE",
		2: "CANCEL_TAKER",
		3: "CANCEL_MAKER",
		4: "CANCEL_BOTH",
	}
	STPMode_value = map[string]int32{
		"STP_UNSPECIFIED": 0,
		"NONE":            1,
		"CANCEL_TAKER":    2,
		"CANCEL_MAKER":    3,
		"CANCEL_BOTH":     4,
	}
)

func (x STPMode) Enum() *STPMode {
	p := new(STPMode)
	*p = x
	return p
}

func (x STPMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STPMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matching_proto_enumTypes[4].Descriptor()
}

func (STPMode) Type() protoreflect.EnumType {
	return &file_proto_matching_proto_enumTypes[4]
}

func (x STPMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STPMode.Descriptor instead.
func (STPMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{4}
}

type TradeEvent_Type int32

const (
	TradeEvent_TRADE        TradeEvent_Type = 0
	TradeEvent_ORDER_UPDATE TradeEvent_Type = 1
)

// Enum value maps for TradeEvent_Type.
var (
	TradeEvent_Type_name = map[int32]string{
		0: "TRADE",
		1: "ORDER_UPDATE",
	}
	TradeEvent_Type_value = map[string]int32{
		"TRADE":        0,
		"ORDER_UPDATE": 1,
	}
)

func (x TradeEvent_Type) Enum() *TradeEvent_Type {
	p := new(TradeEvent_Type)
	*p = x
	return p
}

func (x TradeEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matching_proto_enumTypes[5].Descriptor()
}

func (TradeEvent_Type) Type() protoreflect.EnumType {
	return &file_proto_matching_proto_enumTypes[5]
}

func (x TradeEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeEvent_Type.Descriptor instead.
func (TradeEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{15, 0}
}

type PlaceOrderRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderId string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId  string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pair    string                 `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
	Side    Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=matching.v1.Side" json:"side,omitempty"`
	Type    OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=matching.v1.OrderType" json:"type,omitempty"`
	// Decimal values are encoded as strings to preserve precision.
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TimeInForce   TimeInForce            `protobuf:"varint,8,opt,name=time_in_force,json=timeInForce,proto3,enum=matching.v1.TimeInForce" json:"time_in_force,omitempty"`
	StpMode       STPMode                `protobuf:"varint,9,opt,name=stp_mode,json=stpMode,proto3,enum=matching.v1.STPMode" json:"stp_mode,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	StopPrice     string                 `protobuf:"bytes,11,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ClientId      string                 `protobuf:"bytes,12,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_proto_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *PlaceOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PlaceOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PlaceOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIF_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetStpMode() STPMode {
	if x != nil {
		return x.StpMode
	}
	return STPMode_STP_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PlaceOrderRequest) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *PlaceOrderRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=matching.v1.Status" json:"status,omitempty"`
	Filled        string                 `protobuf:"bytes,3,opt,name=filled,proto3" json:"filled,omitempty"`
	Remaining     string                 `protobuf:"bytes,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,5,rep,name=trades,proto3" json:"trades,omitempty"`
	RejectReason  string                 `protobuf:"bytes,6,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_proto_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *PlaceOrderResponse) GetFilled() string {
	if x != nil {
		return x.Filled
	}
	return ""
}

func (x *PlaceOrderResponse) GetRemaining() string {
	if x != nil {
		return x.Remaining
	}
	return ""
}

func (x *PlaceOrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *PlaceOrderResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_proto_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{3}
}

type AmendOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewPrice      string                 `protobuf:"bytes,3,opt,name=new_price,json=newPrice,proto3" json:"new_price,omitempty"`
	NewQuantity   string                 `protobuf:"bytes,4,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmendOrderRequest) Reset() {
	*x = AmendOrderRequest{}
	mi := &file_proto_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmendOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmendOrderRequest) ProtoMessage() {}

func (x *AmendOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmendOrderRequest.ProtoReflect.Descriptor instead.
func (*AmendOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{4}
}

func (x *AmendOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AmendOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AmendOrderRequest) GetNewPrice() string {
	if x != nil {
		return x.NewPrice
	}
	return ""
}

func (x *AmendOrderRequest) GetNewQuantity() string {
	if x != nil {
		return x.NewQuantity
	}
	return ""
}

type AmendOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmendOrderResponse) Reset() {
	*x = AmendOrderResponse{}
	mi := &file_proto_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmendOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmendOrderResponse) ProtoMessage() {}

func (x *AmendOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmendOrderResponse.ProtoReflect.Descriptor instead.
func (*AmendOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{5}
}

func (x *AmendOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *AmendOrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *AmendOrderResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_proto_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderBookRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetOrderBookRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type GetTickerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerRequest) Reset() {
	*x = GetTickerRequest{}
	mi := &file_proto_matching_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerRequest) ProtoMessage() {}

func (x *GetTickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerRequest.ProtoReflect.Descriptor instead.
func (*GetTickerRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{7}
}

func (x *GetTickerRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_matching_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type StreamTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTradesRequest) Reset() {
	*x = StreamTradesRequest{}
	mi := &file_proto_matching_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTradesRequest) ProtoMessage() {}

func (x *StreamTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTradesRequest.ProtoReflect.Descriptor instead.
func (*StreamTradesRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{9}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pair          string                 `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
	Base          string                 `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	Quote         string                 `protobuf:"bytes,5,opt,name=quote,proto3" json:"quote,omitempty"`
	Side          Side                   `protobuf:"varint,6,opt,name=side,proto3,enum=matching.v1.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,7,opt,name=type,proto3,enum=matching.v1.OrderType" json:"type,omitempty"`
	Price         string                 `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Filled        string                 `protobuf:"bytes,10,opt,name=filled,proto3" json:"filled,omitempty"`
	Remaining     string                 `protobuf:"bytes,11,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Status        Status                 `protobuf:"varint,12,opt,name=status,proto3,enum=matching.v1.Status" json:"status,omitempty"`
	TimeInForce   TimeInForce            `protobuf:"varint,13,opt,name=time_in_force,json=timeInForce,proto3,enum=matching.v1.TimeInForce" json:"time_in_force,omitempty"`
	StpMode       STPMode                `protobuf:"varint,14,opt,name=stp_mode,json=stpMode,proto3,enum=matching.v1.STPMode" json:"stp_mode,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	StopPrice     string                 `protobuf:"bytes,18,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ClientId      string                 `protobuf:"bytes,19,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_matching_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{10}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Order) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Order) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Order) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Order) GetFilled() string {
	if x != nil {
		return x.Filled
	}
	return ""
}

func (x *Order) GetRemaining() string {
	if x != nil {
		return x.Remaining
	}
	return ""
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Order) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIF_UNSPECIFIED
}

func (x *Order) GetStpMode() STPMode {
	if x != nil {
		return x.StpMode
	}
	return STPMode_STP_UNSPECIFIED
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Order) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *Order) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pair          string                 `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	BuyOrderId    string                 `protobuf:"bytes,3,opt,name=buy_order_id,json=buyOrderId,proto3" json:"buy_order_id,omitempty"`
	SellOrderId   string                 `protobuf:"bytes,4,opt,name=sell_order_id,json=sellOrderId,proto3" json:"sell_order_id,omitempty"`
	BuyUserId     string                 `protobuf:"bytes,5,opt,name=buy_user_id,json=buyUserId,proto3" json:"buy_user_id,omitempty"`
	SellUserId    string                 `protobuf:"bytes,6,opt,name=sell_user_id,json=sellUserId,proto3" json:"sell_user_id,omitempty"`
	Base          string                 `protobuf:"bytes,7,opt,name=base,proto3" json:"base,omitempty"`
	Quote         string                 `protobuf:"bytes,8,opt,name=quote,proto3" json:"quote,omitempty"`
	BaseAmount    string                 `protobuf:"bytes,9,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	QuoteAmount   string                 `protobuf:"bytes,10,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
	Price         string                 `protobuf:"bytes,11,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,12,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TakerSide     Side                   `protobuf:"varint,13,opt,name=taker_side,json=takerSide,proto3,enum=matching.v1.Side" json:"taker_side,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_proto_matching_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{11}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Trade) GetBuyOrderId() string {
	if x != nil {
		return x.BuyOrderId
	}
	return ""
}

func (x *Trade) GetSellOrderId() string {
	if x != nil {
		return x.SellOrderId
	}
	return ""
}

func (x *Trade) GetBuyUserId() string {
	if x != nil {
		return x.BuyUserId
	}
	return ""
}

func (x *Trade) GetSellUserId() string {
	if x != nil {
		return x.SellUserId
	}
	return ""
}

func (x *Trade) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Trade) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Trade) GetBaseAmount() string {
	if x != nil {
		return x.BaseAmount
	}
	return ""
}

func (x *Trade) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Trade) GetTakerSide() Side {
	if x != nil {
		return x.TakerSide
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Trade) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

type OrderBookSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookSnapshot) Reset() {
	*x = OrderBookSnapshot{}
	mi := &file_proto_matching_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookSnapshot) ProtoMessage() {}

func (x *OrderBookSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookSnapshot.ProtoReflect.Descriptor instead.
func (*OrderBookSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{12}
}

func (x *OrderBookSnapshot) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *OrderBookSnapshot) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBookSnapshot) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_proto_matching_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{13}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type Ticker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	LastPrice     string                 `protobuf:"bytes,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	BestBid       string                 `protobuf:"bytes,3,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestAsk       string                 `protobuf:"bytes,4,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`
	Volume_24H    string                 `protobuf:"bytes,5,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	High_24H      string                 `protobuf:"bytes,6,opt,name=high_24h,json=high24h,proto3" json:"high_24h,omitempty"`
	Low_24H       string                 `protobuf:"bytes,7,opt,name=low_24h,json=low24h,proto3" json:"low_24h,omitempty"`
	Change_24H    string                 `protobuf:"bytes,8,opt,name=change_24h,json=change24h,proto3" json:"change_24h,omitempty"`
	Trades_24H    int64                  `protobuf:"varint,9,opt,name=trades_24h,json=trades24h,proto3" json:"trades_24h,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_proto_matching_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{14}
}

func (x *Ticker) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Ticker) GetLastPrice() string {
	if x != nil {
		return x.LastPrice
	}
	return ""
}

func (x *Ticker) GetBestBid() string {
	if x != nil {
		return x.BestBid
	}
	return ""
}

func (x *Ticker) GetBestAsk() string {
	if x != nil {
		return x.BestAsk
	}
	return ""
}

func (x *Ticker) GetVolume_24H() string {
	if x != nil {
		return x.Volume_24H
	}
	return ""
}

func (x *Ticker) GetHigh_24H() string {
	if x != nil {
		return x.High_24H
	}
	return ""
}

func (x *Ticker) GetLow_24H() string {
	if x != nil {
		return x.Low_24H
	}
	return ""
}

func (x *Ticker) GetChange_24H() string {
	if x != nil {
		return x.Change_24H
	}
	return ""
}

func (x *Ticker) GetTrades_24H() int64 {
	if x != nil {
		return x.Trades_24H
	}
	return 0
}

func (x *Ticker) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TradeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TradeEvent_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=matching.v1.TradeEvent_Type" json:"type,omitempty"`
	Trade         *Trade                 `protobuf:"bytes,2,opt,name=trade,proto3" json:"trade,omitempty"` // when type == TRADE
	Order         *Order                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"` // when type == ORDER_UPDATE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeEvent) Reset() {
	*x = TradeEvent{}
	mi := &file_proto_matching_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeEvent) ProtoMessage() {}

func (x *TradeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeEvent.ProtoReflect.Descriptor instead.
func (*TradeEvent) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{15}
}

func (x *TradeEvent) GetType() TradeEvent_Type {
	if x != nil {
		return x.Type
	}
	return TradeEvent_TRADE
}

func (x *TradeEvent) GetTrade() *Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

func (x *TradeEvent) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_proto_matching_proto protoreflect.FileDescriptor

const file_proto_matching_proto_rawDesc = "" +
	"\n" +
	"\x14proto/matching.proto\x12\vmatching.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x03\n" +
	"\x11PlaceOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04pair\x18\x03 \x01(\tR\x04pair\x12%\n" +
	"\x04side\x18\x04 \x01(\x0e2\x11.matching.v1.SideR\x04side\x12*\n" +
	"\x04type\x18\x05 \x01(\x0e2\x16.matching.v1.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x12<\n" +
	"\rtime_in_force\x18\b \x01(\x0e2\x18.matching.v1.TimeInForceR\vtimeInForce\x12/\n" +
	"\bstp_mode\x18\t \x01(\x0e2\x14.matching.v1.STPModeR\astpMode\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"stop_price\x18\v \x01(\tR\tstopPrice\x12\x1b\n" +
	"\tclient_id\x18\f \x01(\tR\bclientId\"\xe3\x01\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.matching.v1.StatusR\x06status\x12\x16\n" +
	"\x06filled\x18\x03 \x01(\tR\x06filled\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\tR\tremaining\x12*\n" +
	"\x06trades\x18\x05 \x03(\v2\x12.matching.v1.TradeR\x06trades\x12#\n" +
	"\rreject_reason\x18\x06 \x01(\tR\frejectReason\"H\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x15\n" +
	"\x13CancelOrderResponse\"\x87\x01\n" +
	"\x11AmendOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tnew_price\x18\x03 \x01(\tR\bnewPrice\x12!\n" +
	"\fnew_quantity\x18\x04 \x01(\tR\vnewQuantity\"\x8f\x01\n" +
	"\x12AmendOrderResponse\x12(\n" +
	"\x05order\x18\x01 \x01(\v2\x12.matching.v1.OrderR\x05order\x12*\n" +
	"\x06trades\x18\x02 \x03(\v2\x12.matching.v1.TradeR\x06trades\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\"?\n" +
	"\x13GetOrderBookRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"&\n" +
	"\x10GetTickerRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x15\n" +
	"\x13StreamTradesRequest\"\xb2\x05\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04pair\x18\x03 \x01(\tR\x04pair\x12\x12\n" +
	"\x04base\x18\x04 \x01(\tR\x04base\x12\x14\n" +
	"\x05quote\x18\x05 \x01(\tR\x05quote\x12%\n" +
	"\x04side\x18\x06 \x01(\x0e2\x11.matching.v1.SideR\x04side\x12*\n" +
	"\x04type\x18\a \x01(\x0e2\x16.matching.v1.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\b \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\t \x01(\tR\bquantity\x12\x16\n" +
	"\x06filled\x18\n" +
	" \x01(\tR\x06filled\x12\x1c\n" +
	"\tremaining\x18\v \x01(\tR\tremaining\x12+\n" +
	"\x06status\x18\f \x01(\x0e2\x13.matching.v1.StatusR\x06status\x12<\n" +
	"\rtime_in_force\x18\r \x01(\x0e2\x18.matching.v1.TimeInForceR\vtimeInForce\x12/\n" +
	"\bstp_mode\x18\x0e \x01(\x0e2\x14.matching.v1.STPModeR\astpMode\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"stop_price\x18\x12 \x01(\tR\tstopPrice\x12\x1b\n" +
	"\tclient_id\x18\x13 \x01(\tR\bclientId\"\xc2\x03\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12 \n" +
	"\fbuy_order_id\x18\x03 \x01(\tR\n" +
	"buyOrderId\x12\"\n" +
	"\rsell_order_id\x18\x04 \x01(\tR\vsellOrderId\x12\x1e\n" +
	"\vbuy_user_id\x18\x05 \x01(\tR\tbuyUserId\x12 \n" +
	"\fsell_user_id\x18\x06 \x01(\tR\n" +
	"sellUserId\x12\x12\n" +
	"\x04base\x18\a \x01(\tR\x04base\x12\x14\n" +
	"\x05quote\x18\b \x01(\tR\x05quote\x12\x1f\n" +
	"\vbase_amount\x18\t \x01(\tR\n" +
	"baseAmount\x12!\n" +
	"\fquote_amount\x18\n" +
	" \x01(\tR\vquoteAmount\x12\x14\n" +
	"\x05price\x18\v \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\f \x01(\tR\bquantity\x120\n" +
	"\n" +
	"taker_side\x18\r \x01(\x0e2\x11.matching.v1.SideR\ttakerSide\x12;\n" +
	"\vexecuted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\"\x81\x01\n" +
	"\x11OrderBookSnapshot\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12+\n" +
	"\x04bids\x18\x02 \x03(\v2\x17.matching.v1.PriceLevelR\x04bids\x12+\n" +
	"\x04asks\x18\x03 \x03(\v2\x17.matching.v1.PriceLevelR\x04asks\">\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"\xbd\x02\n" +
	"\x06Ticker\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\tR\tlastPrice\x12\x19\n" +
	"\bbest_bid\x18\x03 \x01(\tR\abestBid\x12\x19\n" +
	"\bbest_ask\x18\x04 \x01(\tR\abestAsk\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x05 \x01(\tR\tvolume24h\x12\x19\n" +
	"\bhigh_24h\x18\x06 \x01(\tR\ahigh24h\x12\x17\n" +
	"\alow_24h\x18\a \x01(\tR\x06low24h\x12\x1d\n" +
	"\n" +
	"change_24h\x18\b \x01(\tR\tchange24h\x12\x1d\n" +
	"\n" +
	"trades_24h\x18\t \x01(\x03R\ttrades24h\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb7\x01\n" +
	"\n" +
	"TradeEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.matching.v1.TradeEvent.TypeR\x04type\x12(\n" +
	"\x05trade\x18\x02 \x01(\v2\x12.matching.v1.TradeR\x05trade\x12(\n" +
	"\x05order\x18\x03 \x01(\v2\x12.matching.v1.OrderR\x05order\"#\n" +
	"\x04Type\x12\t\n" +
	"\x05TRADE\x10\x00\x12\x10\n" +
	"\fORDER_UPDATE\x10\x01*/\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02*>\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\n" +
	"\n" +
	"\x06MARKET\x10\x02*_\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\v\n" +
	"\aPARTIAL\x10\x02\x12\n" +
	"\n" +
	"\x06FILLED\x10\x03\x12\f\n" +
	"\bCANCELED\x10\x04\x12\f\n" +
	"\bREJECTED\x10\x05*=\n" +
	"\vTimeInForce\x12\x13\n" +
	"\x0fTIF_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03GTC\x10\x01\x12\a\n" +
	"\x03IOC\x10\x02\x12\a\n" +
	"\x03FOK\x10\x03*]\n" +
	"\aSTPMode\x12\x13\n" +
	"\x0fSTP_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\x10\n" +
	"\fCANCEL_TAKER\x10\x02\x12\x10\n" +
	"\fCANCEL_MAKER\x10\x03\x12\x0f\n" +
	"\vCANCEL_BOTH\x10\x042\x9f\x04\n" +
	"\x0fMatchingService\x12M\n" +
	"\n" +
	"PlaceOrder\x12\x1e.matching.v1.PlaceOrderRequest\x1a\x1f.matching.v1.PlaceOrderResponse\x12P\n" +
	"\vCancelOrder\x12\x1f.matching.v1.CancelOrderRequest\x1a .matching.v1.CancelOrderResponse\x12M\n" +
	"\n" +
	"AmendOrder\x12\x1e.matching.v1.AmendOrderRequest\x1a\x1f.matching.v1.AmendOrderResponse\x12P\n" +
	"\fGetOrderBook\x12 .matching.v1.GetOrderBookRequest\x1a\x1e.matching.v1.OrderBookSnapshot\x12?\n" +
	"\tGetTicker\x12\x1d.matching.v1.GetTickerRequest\x1a\x13.matching.v1.Ticker\x12<\n" +
	"\bGetOrder\x12\x1c.matching.v1.GetOrderRequest\x1a\x12.matching.v1.Order\x12K\n" +
	"\fStreamTrades\x12 .matching.v1.StreamTradesRequest\x1a\x17.matching.v1.TradeEvent0\x01B<Z:github.com/goexdev/goexchange/internal/matching/matchingv1b\x06proto3"

var (
	file_proto_matching_proto_rawDescOnce sync.Once
	file_proto_matching_proto_rawDescData []byte
)

func file_proto_matching_proto_rawDescGZIP() []byte {
	file_proto_matching_proto_rawDescOnce.Do(func() {
		file_proto_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)))
	})
	return file_proto_matching_proto_rawDescData
}

var file_proto_matching_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_matching_proto_goTypes = []any{
	(Side)(0),                     // 0: matching.v1.Side
	(OrderType)(0),                // 1: matching.v1.OrderType
	(Status)(0),                   // 2: matching.v1.Status
	(TimeInForce)(0),              // 3: matching.v1.TimeInForce
	(STPMode)(0),                  // 4: matching.v1.STPMode
	(TradeEvent_Type)(0),          // 5: matching.v1.TradeEvent.Type
	(*PlaceOrderRequest)(nil),     // 6: matching.v1.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),    // 7: matching.v1.PlaceOrderResponse
	(*CancelOrderRequest)(nil),    // 8: matching.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),   // 9: matching.v1.CancelOrderResponse
	(*AmendOrderRequest)(nil),     // 10: matching.v1.AmendOrderRequest
	(*AmendOrderResponse)(nil),    // 11: matching.v1.AmendOrderResponse
	(*GetOrderBookRequest)(nil),   // 12: matching.v1.GetOrderBookRequest
	(*GetTickerRequest)(nil),      // 13: matching.v1.GetTickerRequest
	(*GetOrderRequest)(nil),       // 14: matching.v1.GetOrderRequest
	(*StreamTradesRequest)(nil),   // 15: matching.v1.StreamTradesRequest
	(*Order)(nil),                 // 16: matching.v1.Order
	(*Trade)(nil),                 // 17: matching.v1.Trade
	(*OrderBookSnapshot)(nil),     // 18: matching.v1.OrderBookSnapshot
	(*PriceLevel)(nil),            // 19: matching.v1.PriceLevel
	(*Ticker)(nil),                // 20: matching.v1.Ticker
	(*TradeEvent)(nil),            // 21: matching.v1.TradeEvent
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_proto_matching_proto_depIdxs = []int32{
	0,  // 0: matching.v1.PlaceOrderRequest.side:type_name -> matching.v1.Side
	1,  // 1: matching.v1.PlaceOrderRequest.type:type_name -> matching.v1.OrderType
	3,  // 2: matching.v1.PlaceOrderRequest.time_in_force:type_name -> matching.v1.TimeInForce
	4,  // 3: matching.v1.PlaceOrderRequest.stp_mode:type_name -> matching.v1.STPMode
	22, // 4: matching.v1.PlaceOrderRequest.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 5: matching.v1.PlaceOrderResponse.status:type_name -> matching.v1.Status
	17, // 6: matching.v1.PlaceOrderResponse.trades:type_name -> matching.v1.Trade
	16, // 7: matching.v1.AmendOrderResponse.order:type_name -> matching.v1.Order
	17, // 8: matching.v1.AmendOrderResponse.trades:type_name -> matching.v1.Trade
	0,  // 9: matching.v1.Order.side:type_name -> matching.v1.Side
	1,  // 10: matching.v1.Order.type:type_name -> matching.v1.OrderType
	2,  // 11: matching.v1.Order.status:type_name -> matching.v1.Status
	3,  // 12: matching.v1.Order.time_in_force:type_name -> matching.v1.TimeInForce
	4,  // 13: matching.v1.Order.stp_mode:type_name -> matching.v1.STPMode
	22, // 14: matching.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	22, // 15: matching.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	22, // 16: matching.v1.Order.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 17: matching.v1.Trade.taker_side:type_name -> matching.v1.Side
	22, // 18: matching.v1.Trade.executed_at:type_name -> google.protobuf.Timestamp
	19, // 19: matching.v1.OrderBookSnapshot.bids:type_name -> matching.v1.PriceLevel
	19, // 20: matching.v1.OrderBookSnapshot.asks:type_name -> matching.v1.PriceLevel
	22, // 21: matching.v1.Ticker.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 22: matching.v1.TradeEvent.type:type_name -> matching.v1.TradeEvent.Type
	17, // 23: matching.v1.TradeEvent.trade:type_name -> matching.v1.Trade
	16, // 24: matching.v1.TradeEvent.order:type_name -> matching.v1.Order
	6,  // 25: matching.v1.MatchingService.PlaceOrder:input_type -> matching.v1.PlaceOrderRequest
	8,  // 26: matching.v1.MatchingService.CancelOrder:input_type -> matching.v1.CancelOrderRequest
	10, // 27: matching.v1.MatchingService.AmendOrder:input_type -> matching.v1.AmendOrderRequest
	12, // 28: matching.v1.MatchingService.GetOrderBook:input_type -> matching.v1.GetOrderBookRequest
	13, // 29: matching.v1.MatchingService.GetTicker:input_type -> matching.v1.GetTickerRequest
	14, // 30: matching.v1.MatchingService.GetOrder:input_type -> matching.v1.GetOrderRequest
	15, // 31: matching.v1.MatchingService.StreamTrades:input_type -> matching.v1.StreamTradesRequest
	7,  // 32: matching.v1.MatchingService.PlaceOrder:output_type -> matching.v1.PlaceOrderResponse
	9,  // 33: matching.v1.MatchingService.CancelOrder:output_type -> matching.v1.CancelOrderResponse
	11, // 34: matching.v1.MatchingService.AmendOrder:output_type -> matching.v1.AmendOrderResponse
	18, // 35: matching.v1.MatchingService.GetOrderBook:output_type -> matching.v1.OrderBookSnapshot
	20, // 36: matching.v1.MatchingService.GetTicker:output_type -> matching.v1.Ticker
	16, // 37: matching.v1.MatchingService.GetOrder:output_type -> matching.v1.Order
	21, // 38: matching.v1.MatchingService.StreamTrades:output_type -> matching.v1.TradeEvent
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_matching_proto_init() }
func file_proto_matching_proto_init() {
	if File_proto_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matching_proto_goTypes,
		DependencyIndexes: file_proto_matching_proto_depIdxs,
		EnumInfos:         file_proto_matching_proto_enumTypes,
		MessageInfos:      file_proto_matching_proto_msgTypes,
	}.Build()
	File_proto_matching_proto = out.File
	file_proto_matching_proto_goTypes = nil
	file_proto_matching_proto_depIdxs = nil
}
